language: node_js
node_js:
  - "8"
install:
  - npm install -g codecov
  - npm install -g mocha
  - npm install -g babel-cli
  - npm install -g nyc
script:
  - npm run build
cache:
  directories:
    - node_modules